# This is a basic workflow to help you get started with Actions

name: Deploy website to Github Pages

on:
  push:
    branches: 
      - master

jobs:
  deploy_docs:
    runs-on: [ ubuntu-latest ]

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        pip install sphinx sphinx_rtd_theme
    - name: Sphinx build
      run: |
        sphinx-build doc _build

    - name: Build docs
      run: |
        sudo apt-get update
        sudo apt-get install -y python3.10-venv doxygen
        python3.10 -m venv tomcat_venv
        source tomcat_venv/bin/activate
        pip install wheel
        pip install -r docs/requirements.txt
        pushd docs > /dev/null
          mkdir build
          cd build
          cmake ..
          make docs
        popd > /dev/null

    - name: Deploy docs to ml4ai.github.io/tomcat
      uses: peaceiris/actions-gh-pages@v3
      with:
        deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        publish_dir: ./docs/build
